
### Simple GET request

GET http://localhost:8080

### Simple GET request returning JSON body, using Result<impl Respnder>

GET http://localhost:8080/api-get-my-animal-result-responder

### Simple POST request

POST http://localhost:8080/echo
content-type: application/json

{
    "name": "sample",
    "activities": ["soccer", "piano"]
}

### GET request: a path with a scope

GET http://localhost:8080/api/api-get
content-type: application/json

### GET request: path with a scope and different sub path

GET http://localhost:8080/api/api-get-b
content-type: application/json


### GET request: path with a scope ("/api") and subscope ("/v1")

GET http://localhost:8080/api/v1/api-v1-get
content-type: application/json

### GET request: path with a scope ("/api") and subscope ("/v1") and a different path

GET http://localhost:8080/api/v1/api-v1-get-b
content-type: application/json

### GET request: path with a scope ("/api") and second subscope ("/v2")

GET http://localhost:8080/api/v2/api-v2-get
content-type: application/json

### GET request: path with a scope ("/api") and second subscope ("/v2") and different path

GET http://localhost:8080/api/v2/api-v2-get-b
content-type: application/json

### GET with query params, both required and optional inputs specified

GET http://localhost:8080/api/v2/api-v2-get-b-query-params?required_input=this-is-required&maybe_other_input=this-is-optional
content-type: application/json

### GET with query params, only required input specified

GET http://localhost:8080/api/v2/api-v2-get-b-query-params?required_input=this-is-required
content-type: application/json

### GET request: path with a scope ("/api") and second subscope ("/v2") and path params (dynamic)

GET http://localhost:8080/api/v2/dynamic_segments/22/turtle
content-type: application/json

### GET request: path with a scope ("/api") and second subscope ("/v2") and path params (struct)

GET http://localhost:8080/api/v2/struct/11/alligator
content-type: application/json

### GET request: path with a scope ("/api") and second subscope ("/v2") and path params (struct) and query params

GET http://localhost:8080/api/v2/struct-path-query/11/alligator?required_input=this-is-required&maybe_other_input=this-is-optional
content-type: application/json

### Rest API with in memory shared mutable state - returns not found

GET http://localhost:8080/api/v2/fruits/99999
content-type: application/json

### Rest API with in memory shared mutable state - returns a match
GET http://localhost:8080/api/v2/fruits/5
content-type: application/json