[package]
name = "user-service"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.21.2", features = ["full"]}
rdkafka = { version = "0.28", features = ["cmake-build"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
log = "0.4.17"